### ISSUE TITLE
Middleware shared memory utility

### ISSUE THREAD

**Issue by benjsherman** [jayspur11/OS_HW3#2]
This block of shared memory will be available for storage
and interprocess communication. The shell will setup the blocks of shared memory and the
required semaphores to control access to the shared memory. Since multiple processes will
have access to the shared memory, the standard shared resource problems will arise. You must
resolve the multiple access (or starvation and deadlock) issues that can occur

**Comment by benjsherman** [comment]
This block of shared memory will be available for storage
and interprocess communication. The shell will setup the blocks of shared memory and the
required semaphores to control access to the shared memory. Since multiple processes will
have access to the shared memory, the standard shared resource problems will arise. You must
resolve the multiple access (or starvation and deadlock) issues that can occur

**Comment by jayspur11** [comment]
- [ ] When this is ready, update the Makefile to include it in compilation.

**Comment by jayspur11** [comment]
I'm beginning to think that the middleware shared memory manager is just the description of the application.
