### ISSUE TITLE
Mailbox Initialization & Removal

### ISSUE THREAD

**Issue by benjsherman** [jayspur11/OS_HW3#3]
- [x] Implement 'mboxinit' method on Mailbox Manager.
- [x] Implement 'mboxdel' method on Mailbox Manager.
- [x] Add 'mboxinit' and 'mboxdel' calls in REP loop.

* Mailbox initialization
  * Usage: mboxinit <number of mailboxes> <size of mailbox in kbytes>
  * Create k+1 blocks
  * k = number of mailboxes requested
  * block size = size of the mailbox
  * The first block of shared memory will contain the mailbox information for all to access.
  * The next k blocks will act as the mailboxes

* Mailbox removal
  * Usage: mboxdel
  * Clean up semaphores and shared memory. This must be done by the creating shell on exit if not before

**Comment by jayspur11** [comment]
Need to ensure that mailboxes get deleted when the creating manager goes out of scope (if they haven't been deleted already).

**Comment by jayspur11** [comment]
I've finished everything I can think of with this, and updated the documentation on it.
