### ISSUE TITLE
Mailbox Data Read-Write-Copy

### ISSUE THREAD

**Issue by benjsherman** [jayspur11/OS_HW3#4]
- [x] Add 'mboxwrite' method
- [x] Add 'mboxread' method
- [x] Add 'mboxcopy' method

- [x] Add methods to REP loop

* Write data
  * Usage: mboxwrite <boxnumber>
  * ... data to be written ...
  * ctrl-d to end
  * Truncate if data is larger than the mailbox and flag user.

* Read data
  * Usage: mboxread <boxnumber>
  * Will read in the text until end of the string or the end of the mailbox is found.

* Copy data
  * Usage: mboxcopy <boxnumber1> <boxnumber2>
  * Copy the contents of one box to another.

**Comment by jayspur11** [comment]
This task has been finished.
