### ISSUE TITLE
Page Replacement Simulator

### ISSUE THREAD

**Issue by benjsherman** [jayspur11/OS_HW3#7]
Simulation of the page replacement algorithms FIFO, Optimal, LRU, LFU,
- Second Chance, 
- Clock.

   Use both reference and distance strings.
   Note: for bit strings - focus only on left entry, right shift.

**Comment by jayspur11** [comment]
- [ ] When this is ready, update the Makefile to include it in compilation.

**Comment by benjsherman** [comment]
Need to add Second Change and Clock Page Replacement Algorithms
